SELECT *
FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP
--------------Exploratory Data Analysis----
----Checking number of coffee shops 
SELECT DISTINCT STORE_LOCATION
FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP;
----Checking number of product category
SELECT DISTINCT PRODUCT_CATEGORY
FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP;
----Checking for first operating date
SELECT MIN(TRANSACTION_DATE) AS FIRST_OPERATING_DATE
FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP;
----Checking for last operating date
SELECT MAX(TRANSACTION_DATE) AS LAST_OPERATING_DATE
FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP;
--Checking for opening hour
SELECT MIN(TRANSACTION_TIME) AS OPENING_HOUR
FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP;
---Checking for closing hour
SELECT Max(TRANSACTION_TIME) AS CLOSING_HOUR
FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP;
---------------
SELECT TRANSACTION_DATE,
    DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
    CASE
         WHEN DAY_NAME IN ('Sat','Sun') THEN 'WEEKEND'
         ELSE 'WEEKDAY'
    END AS DAY_CLASSIFICATION,
    MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME,
    --TRANSACTION_TIME,
    CASE
         WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'Morning'
         WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '16:59:59' THEN 'Afternoon'
         WHEN TRANSACTION_TIME >=  '17:00:00' THEN 'Evening'
    END AS TIME_BUCKET,
    HOUR(TRANSACTION_TIME) AS HOUR_OF_DAY,
    STORE_LOCATION,
    PRODUCT_CATEGORY,
    PRODUCT_DETAIL,
    PRODUCT_TYPE,
    COUNT(DISTINCT TRANSACTION_ID) AS NUMBER_OF_SALES,
    SUM(TRANSACTION_QTY*UNIT_PRICE) AS REVENUE
    FROM CASESTUDY.BRIGHTCOFFEE.COFFEESHOP
    GROUP BY ALL;
